### ISSUE TITLE
11.5 LTS Compatibility

### ISSUE THREAD

**Issue by christophlehmann** [webcoast-dk/versatile-crawler#16]
Hi, do you have plans for TYPO3 11.5 compatibility? :-)

On a first look one need to switch to an alternative hook, see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Deprecation-91012-VariousHooksRelatedToTypoScriptFrontendController.html (`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['hook_eofe']` was removed)

**Comment by thommyhh** [comment]
@christophlehmann Not in terms of time, but I'd surely like to update the crawler for v11. Maybe I can find time after Christmas.

And thanks for the hint about the hooks. Doesn't look too hard.

**Comment by thommyhh** [comment]
@christophlehmann I hope this is still relevant for you. Can you try the `release/2.0` branch? You could also run `composer req webcoast/versatile-crawler ^2.0`, which will get you the `release/2.0` branch until the `2.0.0` release.

**Comment by christophlehmann** [comment]
Hi @thommyhh, thanks for the ping. No. When I remember correctly we used the ext in times where ext crawler wasn't compatible and we then switched back.

Best regards

**Comment by thommyhh** [comment]
@christophlehmann Alright, thanks for letting me know. I guess I'll close it then, as it looks good to me now.
