### ISSUE TITLE
process queue

### ISSUE THREAD

**Issue by blueamerican** [webcoast-dk/versatile-crawler#2]
the process queue seem to work, but i have the following error in the backend protocol:

Core: Error handler (FE): PHP Warning: strcmp() expects parameter 1 to be string, array given in /kunden/nn/rp-hosting/nnn/nn
/typo3cms/muster8/typo3conf/ext/versatile_crawler/Classes/Frontend/IndexHook.php line 31 

![unbenannt-2](https://user-images.githubusercontent.com/5647051/32551487-fea6dcda-c490-11e7-8f0d-25fe24cd44ea.jpg)

**Comment by thommyhh** [comment]
Ok, I will take a look at that.

**Comment by thommyhh** [comment]
@blueamerican Please try version 1.0.1. This includes a fix for the fetching of the header.
