### ISSUE TITLE
PHP warning in belog

### ISSUE THREAD

**Issue by Patta** [webcoast-dk/versatile-crawler#5]
TYPO3 8.7.10 and PHP 7.2.2

> Core: Error handler (FE): PHP Warning: strcmp() expects parameter 1 to be string, array given in /.../web/typo3conf/ext/versatile_crawler/Classes/Frontend/IndexHook.php line 31

**Comment by thommyhh** [comment]
@Patta This should be fixed with version 1.0.1. See issue #2.

**Comment by thommyhh** [comment]
I case you load the extension TER, I just uploaded 1.0.1 there.

**Comment by Patta** [comment]
fixed, thanks!
