### ISSUE TITLE
Error: An error occurred. the call to the url "%s" did not returned a valid json. This could .....

### ISSUE THREAD

**Issue by varioous** [webcoast-dk/versatile-crawler#6]
Hello,

thirst thanks for your extension. I try to use it for indexed_search, because crawler task does not correctly set freeIndexUid.

I have configured the crawler and when i run, i got the error message from FrontendRequestCrawler Link 67. This is because $content from line 57 is the plain html code from the page. And then you do json_decode which does not work, because there is html code and not json.

Did i do anything wrong?

Thanks for your help!
Harald

**Comment by thommyhh** [comment]
Hi Harald,

this sounds like the `WEBcoast\VersatileCrawler\Frontend\IndexHook` is not executed. This could mean the hook is not registered correctly or the Request-Header with the control hash is not provided to the frontend (which would be strange).

Please check `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['hook_eofe']` via the configuration module in the backend, if it contains an entry with the `IndexHook` class. Check also if there are other hooks, that possibly interfere with this one, e.g. if you still have another crawler extension installed/enabled.

If this does not solve the problem, please report which TYPO3 version you are using. I expect, you use version 1.0.1 of this extension?

Regards
Thorben

**Comment by varioous** [comment]
Hello,

yes i am using verison 1.0.1 and Typo3 verison is 8.7.16.

And the entries in the hook:
hook_eofe
0 = WEBcoast\VersatileCrawler\Frontend\IndexHook->indexPage
tx_crawler = AOE\Crawler\Hooks\TsfeHook->fe_eofe

Thanks and kind regards,
Harald

**Comment by thommyhh** [comment]
Ok, this looks like the `crawler` extension is still installed. Please uninstall it and try again.
