### ISSUE TITLE
No RealUrl links in search results

### ISSUE THREAD

**Issue by gvv1401** [webcoast-dk/versatile-crawler#8]
RealUrl is configured and correct works for general pages and details view (news).
But search results without realurl links. 
Link to general page like - http://www.domain.com/index.php?id=64.
Link to details view page like - http://www.domain.com/index.php?id=66&id=66&tx_news_pi1[action]=detail&tx_news_pi1[controller]=News&tx_news_pi1[news]=10&cHash=fa0afb9123e9999e8e68a7636632b5e6 (why page id twice?)
I can not understand whose problem it is? Crawler? IndexedSearch? RealUrl?
Maybe you can give me a clue or a suggestion?

**Comment by thommyhh** [comment]
The duplicate `id` might be the crawlers/indexers mistake when it stuffs the result into the index.

The non-path urls are a matter of the outputting plugin, so indexed_search in this case. But I can't say anything definitively here. Try to debug the search result data in the fluid template and see what it contains. So maybe you are able to identify the problem.

You're welcome to share your findings, if this is a problem with the crawler or not.

**Comment by gvv1401** [comment]
![image](https://user-images.githubusercontent.com/10170885/44309129-9c8ce200-a3ca-11e8-93ca-81b510e4422b.png)
Strange, but  RealUrl is ignored.

**Comment by thommyhh** [comment]
Well, this looks definitely like a bug in indexed_search. Do you have the page id and cHash parameters in the result set? If yes, you should be able to create the link your self using `<f:link.typolink>` view helper. Could be, that you need to `json_decode` og `unserialize` the cHash parameters with a custom view helper before handing it over to the typolink viewhelper.

**Comment by gvv1401** [comment]
Yes, I also think that this is a mistake of indexed_search. I certainly can try different magic and tricks. But I'm interested when TYPO3 will finally have a normal search engine?
Thanks for support!

**Comment by thommyhh** [comment]
You're welcome. :-) Yes good question, I planned on working something out for that too, but that will be another story.

I'm closing this then.

**Comment by gvv1401** [comment]
Yes, sure.
